########################################################
## USB Host Interface Signal
########################################################
## FMC
set_property PACKAGE_PIN AP9  [get_ports "SL_DT[0]"]         
set_property PACKAGE_PIN AR9  [get_ports "SL_DT[1]"]         
set_property PACKAGE_PIN AP8  [get_ports "SL_DT[2]"]         
set_property PACKAGE_PIN AR8  [get_ports "SL_DT[3]"]         
set_property PACKAGE_PIN AH13 [get_ports "SL_DT[4]"]         
set_property PACKAGE_PIN AJ13 [get_ports "SL_DT[5]"]         
set_property PACKAGE_PIN AJ12 [get_ports "SL_DT[6]"]         
set_property PACKAGE_PIN AK12 [get_ports "SL_DT[7]"]         
set_property PACKAGE_PIN AG12 [get_ports "SL_DT[8]"]         
set_property PACKAGE_PIN AH12 [get_ports "SL_DT[9]"]         
set_property PACKAGE_PIN AM8  [get_ports "SL_DT[10]"]        
set_property PACKAGE_PIN AM7  [get_ports "SL_DT[11]"]        
set_property PACKAGE_PIN AL8  [get_ports "SL_DT[12]"]        
set_property PACKAGE_PIN AL7  [get_ports "SL_DT[13]"]        
set_property PACKAGE_PIN AK13 [get_ports "SL_DT[14]"]        
set_property PACKAGE_PIN AL12 [get_ports "SL_DT[15]"]        
set_property PACKAGE_PIN AJ14 [get_ports "SL_DT[16]"]        
set_property PACKAGE_PIN AK14 [get_ports "SL_DT[17]"]        
set_property PACKAGE_PIN AR12 [get_ports "SL_DT[18]"]        
set_property PACKAGE_PIN AR11 [get_ports "SL_DT[19]"]        
set_property PACKAGE_PIN AN21 [get_ports "SL_DT[20]"]        
set_property PACKAGE_PIN AP21 [get_ports "SL_DT[21]"]        
set_property PACKAGE_PIN AM20 [get_ports "SL_DT[22]"]        
set_property PACKAGE_PIN AN20 [get_ports "SL_DT[23]"]        
set_property PACKAGE_PIN AU20 [get_ports "SL_DT[24]"]        
set_property PACKAGE_PIN AU19 [get_ports "SL_DT[25]"]        
set_property PACKAGE_PIN AR17 [get_ports "SL_DT[26]"]        
set_property PACKAGE_PIN AT17 [get_ports "SL_DT[27]"]        
set_property PACKAGE_PIN AM19 [get_ports "SL_DT[28]"]        
set_property PACKAGE_PIN AR19 [get_ports "SL_DT[29]"]        
set_property PACKAGE_PIN AT19 [get_ports "SL_DT[30]"]        
set_property PACKAGE_PIN AM18 [get_ports "SL_DT[31]"]        
                         
set_property PACKAGE_PIN AL9  [get_ports "SL_PCLK"]          
set_property PACKAGE_PIN AM9  [get_ports "SL_CS_N"]          
set_property PACKAGE_PIN AN8  [get_ports "SL_WR_N"]          
set_property PACKAGE_PIN AN7  [get_ports "SL_OE_N"]          
set_property PACKAGE_PIN AM12 [get_ports "SL_RD_N"]          
                         
set_property PACKAGE_PIN AN12 [get_ports "SL_FLAGA"]         
set_property PACKAGE_PIN AT10 [get_ports "SL_FLAGB"]         
set_property PACKAGE_PIN AU10 [get_ports "SL_FLAGC"]         
set_property PACKAGE_PIN AM10 [get_ports "SL_FLAGD"]         
                         
set_property PACKAGE_PIN AL10 [get_ports "SL_PKTEND_N"]      
set_property PACKAGE_PIN AM13 [get_ports "SL_RST_N"]         
set_property PACKAGE_PIN AL14 [get_ports "SL_AD[1]"]         
set_property PACKAGE_PIN AM14 [get_ports "SL_AD[0]"]         
                         
set_property PACKAGE_PIN AN13 [get_ports "SL_MODE[0]"]       
set_property PACKAGE_PIN AL19 [get_ports "SL_MODE[1]"]       

set_property IOSTANDARD LVCMOS18    [get_ports {SL_*}]
set_property SLEW       FAST        [get_ports {SL_*}]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SL_MODE_IBUF[0]_inst/O]
#
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_DT_O_reg*}]
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_RD_N_reg}]
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_WR_N_reg}]
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_OE_N_reg}]
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_PKTEND_N_reg}]
#set_property IOB TRUE  [get_cells {u_dut/u_master/SL_AD_reg*}]
